name: Production Deployment
on:
  release:
    types: [published]
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: nurimansyah/hello-world:latest,nurimansyah/hello-world:${{ github.ref_name }}

  update-version:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
      - name: Checkout chart
        uses: actions/checkout@v3
        with:
          repository: devguystory/helm-private-charts
          token: ${{ secrets.GH_PAT }}
          path: helm-private-charts
          
      - name: Setup helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        
      - name: Update chart versions
        run: |
          cd helm-private-charts/charts/hello-world
          perl -i -pe 's/(version: )(\d+\.\d+\.)(\d+)$/$1.$2.($3+1)/e' Chart.yaml
          perl -i -pe 's/(appVersion: )(".+")$/$1."\"${{ github.ref_name }}\""/e' Chart.yaml

      - name: Update chart image
        env:
          IMAGE_NAME: nurimansyah/hello-world:${{ github.ref_name }}
        run: |
          cd helm-private-charts/charts/hello-world
          perl -i -pe 's/(image: )(.+)$/$1.$ENV{IMAGE_NAME}/e' values.yaml
          
      - name: Generate files
        run: |
          cd helm-private-charts/files
          helm package ../charts/hello-world/
          
      - name: Indexing helm repo
        run: |
          cd helm-private-charts
          helm repo index .
          
      - name: Update helm repo
        run: |
          cd helm-private-charts
          git config user.name "Github Action"
          git config user.email "no-reply@github.com"
          git add -A && git commit -m "release:hello-world:${{ github.ref_name }}" && git push https://${{ secrets.GH_PAT }}@github.com/devguystory/helm-private-charts.git